CREATE TABLE topicos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    mensagem TEXT,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estado ENUM('NAO_RESPONDIDO', 'RESPONDIDO', 'FECHADO') DEFAULT 'NAO_RESPONDIDO',
    autor VARCHAR(255),
    curso VARCHAR(255)
);